# Generated by Django 2.2.7 on 2019-12-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20191203_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='first_name',
        ),
    ]
